export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_EXISTING = 'LOGIN_EXISTING'
export const LOGOUT = 'LOGOUT'

export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'

export const CREATE_ASANA_INSTANCE = 'CREATE_ASANA_INSTANCE'
export const FETCH_ASANA_INSTANCES = 'FETCH_ASANA_INSTANCES'
export const SET_ASANA_INSTANCE_DATA = 'SET_ASANA_INSTANCE_DATA'
export const DELETE_ASANA_INSTANCE = 'DELETE_ASANA_INSTANCE'

export const CREATE_ASANA = 'CREATE_ASANA'
export const ASANA_SUCCESS = 'ASANA_SUCCESS'
export const ASANA_ERROR = 'ASANA_ERROR'
export const FETCH_ASANAS = 'FETCH_ASANAS'
export const SET_ASANAS = 'SET_ASANAS'

export const UPDATE_SEQUENCE = 'UPDATE_SEQUENCE'
export const FETCH_SEQUENCE  = 'FETCH_SEQUENCE'
export const FETCH_SEQUENCES  = 'FETCH_SEQUENCES'
export const SET_SEQUENCE = 'SET_SEQUENCE'
